jobs:
- deployment: VMDeploy
  displayName: web
  pool:
    vmImage: 'Ubuntu-16.04'
  environment:
    name: <environment name>
    resourceType: VirtualMachine
  strategy:
      runOnce:
        deploy:
          steps:
          - script: echo my first deployment